src/djangoaddicts/modelnotes/urls.py
from django.urls import path
from .views import gui
from .views import htmx
from .views import ajax

app_name = 'modelnotes'

urlpatterns = [
    # list views
    path('list_my_notes/', gui.ListMyNotes.as_view(), name='list_my_notes'),
    path('list_group_notes/', gui.ListGroupNotes.as_view(), name='list_group_notes'),
    path('list_readable_notes/', gui.ListReadableNotes.as_view(), name='list_readable_notes'),
    path('list_all_notes/', gui.ListAllNotes.as_view(), name='list_all_notes'),

    # ajax views
    path('get_note_details', ajax.get_note_details, name='get_note_details'),
    path('get_note_auditlog', ajax.get_note_auditlog, name='get_note_auditlog'),

    # htmx views
    path('create_note', htmx.CreateNote.as_view(), name='create_note'),
    path('retrieve_notes', htmx.RetrieveNotes.as_view(), name='retrieve_notes'),
    path('update_note/<int:pk>/', htmx.UpdateNote.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', htmx.DeleteNote.as_view(), name='delete_note'),
    path('get_scope_fields/', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_scope_fields/<int:pk>', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_notes_for_instance/', htmx.GetNotesForInstance.as_view(), name='get_notes_for_instance'),


]

src/modelnotes/urls.py
from django.urls import path
from modelnotes.views import gui
from modelnotes.views import htmx
from modelnotes.views import ajax

app_name = 'modelnotes'

urlpatterns = [
    # list views
    path('list_my_notes/', gui.ListMyNotes.as_view(), name='list_my_notes'),
    path('list_group_notes/', gui.ListGroupNotes.as_view(), name='list_group_notes'),
    path('list_readable_notes/', gui.ListReadableNotes.as_view(), name='list_readable_notes'),
    path('list_all_notes/', gui.ListAllNotes.as_view(), name='list_all_notes'),

    # ajax views
    path('get_note_details', ajax.get_note_details, name='get_note_details'),
    path('get_note_auditlog', ajax.get_note_auditlog, name='get_note_auditlog'),

    # htmx views
    path('create_note', htmx.CreateNote.as_view(), name='create_note'),
    path('retrieve_notes', htmx.RetrieveNotes.as_view(), name='retrieve_notes'),
    path('update_note/<int:pk>/', htmx.UpdateNote.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', htmx.DeleteNote.as_view(), name='delete_note'),
    path('get_scope_fields/', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_scope_fields/<int:pk>', htmx.GetScopeFields.as_view(), name='get_scope_fields'),

]

src/djangoaddicts/modelnotes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'content', 'scope', 'groups', 'public_permissions']

src/modelnotes/forms.py
from django import forms

from modelnotes.models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'content', 'scope', 'groups', 'public_permissions']

src/djangoaddicts/modelnotes/views/action.py
from django.apps import apps
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.views.generic import View, DeleteView
from braces.views import LoginRequiredMixin


# import models
from django.contrib.auth.models import Group
from djangoaddicts.modelnotes.models import (Scope, Permission, Note)


def check_managability(user, note, action):
    """
    Determine if user can edit or delete this note. This note can be edited or deleted if at least one of the
    following criteria is met:
        - user is an admin
        - user is the author of the note
        - user is member of a group in groups AND note is proper permission is set
        - note is public and proper permission is set

    Args:
        user: django User object
        note: Note object
        action: (str) name of action to check for (edit or delete)

    Returns (bool):
        True if this note can be managed by the provided user
        False if this note can not be managed by the provided user
    """
    if action not in 'readeditdelete':
        return False
    if user.is_superuser:
        return True
    if note.author == user:
        return True
    if note.scope.name == 'group' and \
            any(i in user.groups.all() for i in note.groups.all()) and \
            action in [i.name for i in note.public_permissions.all()]:
        return True
    if note.scope.name == 'public' and action in [i.name for i in note.public_permissions.all()]:
        return True
    return False


class CreateNote(LoginRequiredMixin, View):
    """ create a note """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        label = self.request.GET.dict().get('model', None)
        obj_id = self.request.GET.dict().get('id', None)
        title = self.request.GET.dict().get('title', None)
        scope_name = self.request.GET.dict().get('scope', None)
        groups = self.request.GET.dict().get('groups', None)
        permissions = self.request.GET.dict().get('permissions', None)
        content = self.request.GET.dict().get('content', None)

        try:
            if scope_name:
                scope = Scope.objects.get(name=scope_name)
            else:
                scope = None
            note = Note.objects.create(
                title=title,
                author=request.user,
                scope=scope,
                content=content,
                content_type=ContentType.objects.get(app_label=label.split('.')[0], model=label.split('.')[1]),
                object_id=obj_id,
            )

            if scope.name == 'group':
                group_list = Group.objects.filter(name__in=groups.split(','))
                for group in group_list:
                    if group not in note.groups.all():
                        note.groups.add(group)

            elif scope.name == 'public':
                permission_list = Permission.objects.filter(name__in=permissions.split(','))
                for permission in permission_list:
                    if permission not in note.public_permissions.all():
                        note.public_permissions.add(permission)

            messages.add_message(self.request, messages.INFO, f'note {note} successfully created',
                                 extra_tags='alert-info')
        except Exception as err:
            messages.add_message(request, messages.ERROR, str(err), extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))


class UpdateNote(LoginRequiredMixin, View):
    """ update a note """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        obj_id = self.request.GET.dict().get('id', None)
        title = self.request.GET.dict().get('title', None)
        scope_name = self.request.GET.dict().get('scope', None)
        groups = self.request.GET.dict().get('groups', None)
        permissions = self.request.GET.dict().get('permissions', None)
        content = self.request.GET.dict().get('content', None)
        new_groups = Group.objects.filter(name__in=groups.split(','))
        new_permissions = Permission.objects.filter(name__in=permissions.split(','))
        try:
            note = Note.objects.get_object_or_none(id=obj_id)
            scope = Scope.objects.get(name=scope_name)
            if check_managability(request.user, note, 'edit'):
                note.title = title
                note.scope = scope
                note.content = content

                # remove attached groups if note scope is not group
                if scope.name != 'group':
                    note.groups.remove(*note.groups.all())

                # remove attached public_permissions if note scope is not public
                if scope.name != 'public':
                    note.public_permissions.remove(*note.public_permissions.all())

                if scope.name == 'group':
                    for group in new_groups:
                        if group not in note.groups.all():
                            note.groups.add(group)
                    for group in note.groups.all():
                        if group not in new_groups:
                            note.groups.remove(group)

                if scope.name == 'public':
                    for permission in new_permissions:
                        if permission not in note.public_permissions.all():
                            note.public_permissions.add(permission)
                    for permission in note.public_permissions.all():
                        if permission not in new_permissions:
                            note.public_permissions.remove(permission)

                note.save()
                messages.add_message(self.request, messages.INFO, f'note {note} successfully updated',
                                     extra_tags='alert-info')
            else:
                messages.add_message(self.request, messages.ERROR, f'This note can not be updated by {request.user}',
                                     extra_tags='alert-danger')
        except Exception as err:
            messages.add_message(request, messages.ERROR, err, extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))


class DeleteNote(LoginRequiredMixin, DeleteView):
    """ delete a note (by pk) and return to the referring page """
    def delete(self, request, *args, **kwargs):
        note = Note.objects.get(**kwargs)
        if check_managability(request.user, note, 'delete'):
            note.delete()
            messages.add_message(self.request, messages.INFO, 'note successfully deleted', extra_tags='alert-info')
        else:
            messages.add_message(self.request, messages.ERROR, f'This note can not be deleted by {request.user}',
                                 extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))

src/djangoaddicts/modelnotes/views/ajax.py
import json

from django.conf import settings
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.http import require_GET

from djangoaddicts.modelnotes.views.action import check_managability

# import models
if 'auditlog' in settings.INSTALLED_APPS:
    from auditlog.models import LogEntry
from djangoaddicts.modelnotes.models import Note


@require_GET
def get_note_details(request):
    """
    Description:
        get details for a given Note.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'client_response' in request.GET:
            object_id = request.GET['client_response']
            instance = Note.objects.get(id=object_id)
            if not check_managability(request.user, instance, 'read'):
                return HttpResponse('Insufficient permissions', status=403)
            template = loader.get_template('modelnotes/ajax/detail_note.htm')
            return HttpResponse(json.dumps({'server_response': template.render({'object': instance})}),
                                content_type='application/javascript')
        else:
            return HttpResponse('Invalid request inputs', status=400)
    else:
        return HttpResponse('Invalid request', status=400)


@require_GET
def get_note_auditlog(request):
    """
    Description:
        get AuditLog for a given Note.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'auditlog' not in settings.INSTALLED_APPS:
            return HttpResponse('auditlog is not installed', status=400)
        if 'client_response' in request.GET:
            object_id = request.GET['client_response']
            instance = Note.objects.get(id=object_id)
            if not check_managability(request.user, instance, 'read'):
                return HttpResponse('Insufficient permissions', status=403)
            queryset = LogEntry.objects.filter(content_type__model='note',
                                               object_id=object_id)
            template = loader.get_template('handyhelpers/ajax/show_audit_log.htm')
            return HttpResponse(json.dumps({'server_response': template.render({'queryset': queryset})}),
                                content_type='application/javascript')
        else:
            return HttpResponse('Invalid request inputs', status=400)
    else:
        return HttpResponse('Invalid request', status=400)

src/djangoaddicts/modelnotes/views/gui.py
from django.conf import settings

from braces.views import SuperuserRequiredMixin
from handyhelpers.views import HandyHelperListPlusCreateAndFilterView

from djangoaddicts.modelnotes.helpers import get_all_notes, get_group_notes, get_user_notes, get_readable_notes


class ListNotesBaseView(HandyHelperListPlusCreateAndFilterView):
    base_template = getattr(settings, 'BASE_TEMPLATE', 'handyhelpers/handyhelpers_base_bs5.htm')
    template = 'handyhelpers/generic/bs5/generic_list.html'


class ListMyNotes(ListNotesBaseView):
    """ get modelnotes where user is the author """
    title = 'Notes'
    page_description = 'my notes'
    table = 'modelnotes/table/notes.htm'

    def get(self, request, *args, **kwargs):
        self.queryset = get_user_notes(user=request.user)
        return super().get(request, *args, **kwargs)


class ListGroupNotes(ListNotesBaseView):
    """  get modelnotes with a scope of 'group' and authored by a member of a group user is also a member of """
    title = 'Notes'
    page_description = 'group'
    table = 'modelnotes/table/notes.htm'

    def get(self, request, *args, **kwargs):
        self.queryset = get_group_notes(user=request.user)
        return super().get(request, *args, **kwargs)



class ListReadableNotes(ListNotesBaseView):
    """ get modelnotes that current user can read:
        - authored by user
        - with a scope of 'group' and authored by a member of a group user is also a member of
        - with a scope of 'public'
    """
    title = 'Notes'
    page_description = 'readable'
    table = 'modelnotes/table/notes.htm'

    def get(self, request, *args, **kwargs):
        self.queryset = get_readable_notes(user=request.user)
        return super().get(request, *args, **kwargs)


class ListAllNotes(ListNotesBaseView, SuperuserRequiredMixin):
    """ get modelnotes all modelnotes (only available to superusers) """
    title = 'Notes'
    page_description = 'readable'
    table = 'modelnotes/table/notes.htm'

    def get(self, request, *args, **kwargs):
        self.queryset = get_all_notes(user=request.user)
        return super().get(request, *args, **kwargs)

src/modelnotes/views/ajax.py
import json

from django.conf import settings
from django.http import HttpResponse
from django.template import loader
from django.views.decorators.http import require_GET

from modelnotes.views.action import check_managability

# import models
if 'auditlog' in settings.INSTALLED_APPS:
    from auditlog.models import LogEntry
from modelnotes.models import Note


@require_GET
def get_note_details(request):
    """
    Description:
        get details for a given Note.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'client_response' in request.GET:
            object_id = request.GET['client_response']
            instance = Note.objects.get(id=object_id)
            if not check_managability(request.user, instance, 'read'):
                return HttpResponse('Insufficient permissions', status=403)
            template = loader.get_template('modelnotes/ajax/detail_note.htm')
            return HttpResponse(json.dumps({'server_response': template.render({'object': instance})}),
                                content_type='application/javascript')
        else:
            return HttpResponse('Invalid request inputs', status=400)
    else:
        return HttpResponse('Invalid request', status=400)


@require_GET
def get_note_auditlog(request):
    """
    Description:
        get AuditLog for a given Note.
    Args:
        request: AJAX request object.
    Returns:
        HttpResponse: JSON formatted response.
    """
    if (request.is_ajax()) and (request.method == 'GET'):
        if 'auditlog' not in settings.INSTALLED_APPS:
            return HttpResponse('auditlog is not installed', status=400)
        if 'client_response' in request.GET:
            object_id = request.GET['client_response']
            instance = Note.objects.get(id=object_id)
            if not check_managability(request.user, instance, 'read'):
                return HttpResponse('Insufficient permissions', status=403)
            queryset = LogEntry.objects.filter(content_type__model='note',
                                               object_id=object_id)
            template = loader.get_template('handyhelpers/ajax/show_audit_log.htm')
            return HttpResponse(json.dumps({'server_response': template.render({'queryset': queryset})}),
                                content_type='application/javascript')
        else:
            return HttpResponse('Invalid request inputs', status=400)
    else:
        return HttpResponse('Invalid request', status=400)

src/djangoaddicts/modelnotes/templates/modelnotes/_generic_htmx_list.html
<div class="container-fluid animated fadeIn mb-5">
    <h1><span class="text-primary"><b>{{ title }}:</b></span> {% if subtitle %}<span class="text-secondary"><small><small>{{ subtitle }}</small></small></span>{% endif %}</h1>
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- Font Awesome -->
        <link href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

        <!-- animate.css -->
        <link href="{% static 'node_modules/animate.css/animate.min.css' %}" rel="stylesheet">

        <!-- Bootstrap -->
        <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">

        <!-- htmx -->
        <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>


        <style>
        body {
            background-color: #E6E6E6;
        }
        </style>
    </head>

    <body>
    <div class="container">
        {% comment %}
        <div class="text-right">
            <a href="#" hx-get="{% url 'modelnotes:create_note' %}" hx-target="#create_update_modal_wrapper">
                <span class="mx-1 hvr-grow"><i class="fas fa-add text-primary"></i></span>
            </a>
        </div>
        {% endcomment %}

    <!-- wrapper for the table (will be dynamically loaded via htmx) -->
<!--    <div hx-trigger="load, instanceListChanged from:body" hx-get="{% url 'modelnotes:retrieve_notes' %}" hx-target="this">-->
<!--    </div>-->

    {% if table %}{% include table %}{% endif %}

    <!-- wrapper for the create/update note form modal -->
    <div id="create_update_modal_wrapper">
    {% with 'create_update_modal' as modal_id %}
    {% include 'modelnotes/htmx/generic_modal.htm' %}
    {% include 'modelnotes/htmx/generic_modal_js.htm' %}
    {% endwith %}
    </div>

    <!-- wrapper for the delete confirmation modal -->
    <div id="delete_confirmation_modal_wrapper">
    {% with 'delete_confirmation_modal' as modal_id %}
    {% include 'modelnotes/htmx/generic_modal.htm' %}
    {% include 'modelnotes/htmx/generic_modal_js.htm' %}
    {% endwith %}
    </div>

    <!-- Empty toast to show the message -->
    {% include 'modelnotes/htmx/toast.htm' %}

    </body>
</html>

src/djangoaddicts/modelnotes/templates/modelnotes/generic_list_view.html
{% extends base_template|default:"handyhelpers/handyhelpers_base_bs5.htm" %}
{% load static %}
{% load handyhelper_tags %}

{% block local_head %}
    <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>
    {% include "handyhelpers/component/bs5/table_components.htm" %}
{% endblock %}

{% block content %}
{% load handyhelper_tags %}
<div class="container-fluid animated fadeIn mb-5">
    <h1><span class="text-primary"><b>{{ title }}:</b></span> {% if subtitle %}<span class="text-secondary"><small><small>{{ subtitle }}</small></small></span>{% endif %}</h1>

    {% include table %}

</div>

<!-- wrapper for the create/update note form modal -->
<div id="create_update_modal_wrapper">
{% with 'create_update_modal' as modal_id %}
{% include 'modelnotes/htmx/generic_modal.htm' %}
{% include 'modelnotes/htmx/generic_modal_js.htm' %}
{% endwith %}
</div>

<!-- wrapper for the delete confirmation modal -->
<div id="delete_confirmation_modal_wrapper">
{% with 'delete_confirmation_modal' as modal_id %}
{% include 'modelnotes/htmx/generic_modal.htm' %}
{% include 'modelnotes/htmx/generic_modal_js.htm' %}
{% endwith %}
</div>

<!-- Empty toast to show the message -->
{% include 'modelnotes/htmx/toast.htm' %}

{% endblock content %}

src/djangoaddicts/modelnotes/templates/modelnotes/test.html
<div class="container-fluid animated fadeIn mb-5">
    <h1><span class="text-primary"><b>{{ title }}:</b></span> {% if subtitle %}<span class="text-secondary"><small><small>{{ subtitle }}</small></small></span>{% endif %}</h1>
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>

        <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
        <link href="{% static 'node_modules/hover.css/css/hover.css' %}" rel="stylesheet">
        <link href="{% static 'node_modules/animate.css/animate.min.css' %}" rel="stylesheet">

    </head>

    <body>
        <div class="container">
            {% comment %}
            <div class="container text-right">
                <a href="#" hx-get="{% url 'modelnotes:create_note' %}" hx-target="#create_update_modal_wrapper">
                    <span class="mx-1 hvr-grow"><i class="fas fa-add text-primary"></i></span>
                </a>
            </div>
            {% endcomment %}

            {% comment %}
            {% endcomment %}
            <!-- wrapper for the table (will be dynamically loaded via htmx) -->
            <div hx-trigger="load, instanceListChanged from:body" hx-get="{% url 'modelnotes:retrieve_notes' %}" hx-target="this">
            </div>

            <!-- wrapper for the create/update note form modal -->
            <div id="create_update_modal_wrapper">
            {% with 'create_update_modal' as modal_id %}
            {% include 'modelnotes/snippet/htmx_modal.htm' %}
            {% endwith %}
            </div>

            <!-- wrapper for the delete confirmation modal -->
            <div id="delete_confirmation_modal_wrapper">
            {% with 'delete_confirmation_modal' as modal_id %}
            {% include 'modelnotes/snippet/htmx_modal.htm' %}
            {% endwith %}
            </div>

            <!-- Empty toast to show the message -->
            {% include 'modelnotes/htmx/toast.htm' %}
        </div>
    </body>
</html>