src/djangoaddicts/modelnotes/urls.py
from django.urls import path
from .views import gui
from .views import htmx
from .views import ajax

app_name = 'modelnotes'

urlpatterns = [
    # list views
    path('list_my_notes/', gui.ListMyNotes.as_view(), name='list_my_notes'),
    path('list_group_notes/', gui.ListGroupNotes.as_view(), name='list_group_notes'),
    path('list_readable_notes/', gui.ListReadableNotes.as_view(), name='list_readable_notes'),
    path('list_all_notes/', gui.ListAllNotes.as_view(), name='list_all_notes'),

    # ajax views
    path('get_note_details', ajax.get_note_details, name='get_note_details'),
    path('get_note_auditlog', ajax.get_note_auditlog, name='get_note_auditlog'),

    # htmx views
    path('create_note', htmx.CreateNote.as_view(), name='create_note'),
    path('retrieve_notes', htmx.RetrieveNotes.as_view(), name='retrieve_notes'),
    path('update_note/<int:pk>/', htmx.UpdateNote.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', htmx.DeleteNote.as_view(), name='delete_note'),
    path('get_scope_fields/', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_scope_fields/<int:pk>', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_notes_for_instance/', htmx.GetNotesForInstance.as_view(), name='get_notes_for_instance'),


]

src/modelnotes/urls.py
from django.urls import path
from modelnotes.views import gui
from modelnotes.views import htmx
from modelnotes.views import ajax

app_name = 'modelnotes'

urlpatterns = [
    # list views
    path('list_my_notes/', gui.ListMyNotes.as_view(), name='list_my_notes'),
    path('list_group_notes/', gui.ListGroupNotes.as_view(), name='list_group_notes'),
    path('list_readable_notes/', gui.ListReadableNotes.as_view(), name='list_readable_notes'),
    path('list_all_notes/', gui.ListAllNotes.as_view(), name='list_all_notes'),

    # ajax views
    path('get_note_details', ajax.get_note_details, name='get_note_details'),
    path('get_note_auditlog', ajax.get_note_auditlog, name='get_note_auditlog'),

    # htmx views
    path('create_note', htmx.CreateNote.as_view(), name='create_note'),
    path('retrieve_notes', htmx.RetrieveNotes.as_view(), name='retrieve_notes'),
    path('update_note/<int:pk>/', htmx.UpdateNote.as_view(), name='update_note'),
    path('delete_note/<int:pk>/', htmx.DeleteNote.as_view(), name='delete_note'),
    path('get_scope_fields/', htmx.GetScopeFields.as_view(), name='get_scope_fields'),
    path('get_scope_fields/<int:pk>', htmx.GetScopeFields.as_view(), name='get_scope_fields'),

]

src/djangoaddicts/modelnotes/models.py
from django.apps import apps
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db.models import Q
from handyhelpers.managers import HandyHelperModelManager
from handyhelpers.models import HandyHelperBaseModel
from .helpers import get_all_notes

if 'auditlog' in settings.INSTALLED_APPS:
    from auditlog.registry import auditlog
    from auditlog.models import AuditlogHistoryField


def get_default_scope():
    """ get the default scope """
    return Scope.objects.get_or_create(name='private')[0]


class ReadableNotesManager(HandyHelperModelManager):

    def all(self, *args, **kwargs):
        """ only allow retrieval of notes that user can read; return empty queryset if user note provided """
        user = kwargs.get('user', None)
        if not user:
            return Note.objects.none()
        return self.get_queryset().complex_filter(
                Q(author=user) |
                Q(groups__user=user, scope__name='group') |
                Q(scope__name='public')
            )

    def filter(self, *args, **kwargs):
        """ only allow retrieval of notes that user can read; return empty queryset if user note provided """
        user = kwargs.pop('user', None)
        if not user:
            return Note.objects.none()
        return self.get_queryset()._filter_or_exclude(False, args, kwargs).complex_filter(
                Q(author=user) |
                Q(groups__user=user, scope__name='group') |
                Q(scope__name='public')
            )

class Scope(HandyHelperBaseModel):
    """ Track the scope of a note; build-in scopes include:
        private - viewable only to the author
        group   - viewable to members of groups set in the groups field
        public  - viewable to everyone
    """
    name = models.CharField(max_length=16, unique=True, help_text='name of this scope')
    description = models.CharField(max_length=16, help_text='description of this scope')

    def __str__(self):
        return self.name


class Permission(HandyHelperBaseModel):
    """ Track the permissions of a note; build-in permissions include:
        read   - allowed to view note
        edit   - allowed to edit note
        delete - allowed to delete note
    """
    name = models.CharField(max_length=16, unique=True, help_text='permission')
    description = models.CharField(max_length=16, help_text='description of this permission')

    def __str__(self):
        return self.name


class Note(HandyHelperBaseModel):
    """
    if scope is group, any member of the group can perform actions as set in permissions
    """
    title = models.CharField(max_length=32, help_text='title for this note')
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL,
                               help_text='user who created this note')
    scope = models.ForeignKey(Scope, blank=True, default=get_default_scope,
                              on_delete=get_default_scope, help_text='sets access to this note')
    public_permissions = models.ManyToManyField(Permission, blank=True, through='PublicPermission',
                                                help_text='indicated actions that can be performed on this note when '
                                                          'scope is set to public')
    groups = models.ManyToManyField(Group, blank=True, through='GroupPermission')
    content = models.TextField(help_text='the actual content of this note')
    content_type = models.ForeignKey(ContentType, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(blank=True)
    object_repr = models.CharField(max_length=128, blank=True, null=True,
                                   help_text='string representation of an object instance')
    content_object = GenericForeignKey('content_type', 'object_id')
    if 'auditlog' in settings.INSTALLED_APPS:
        history = AuditlogHistoryField()

    objects = ReadableNotesManager()

    def clean(self):
        """ runs validations before saving """
        def verify_object_instance_exists():
            """ Check that the instance of an object, as identified by object_id, exists. If not, do not allow
            note to be attached. """
            if getattr(self, 'content_type', None) and getattr(self, 'object_id', None):
                try:
                    content_type_object = ContentType.objects.get(id=self.content_type.id)
                    model_class = apps.get_model(app_label=content_type_object.app_label,
                                                 model_name=content_type_object.model)
                except Exception as err:
                    raise ValidationError({'object_id': f'Failed to attach note: {err}'})
                try:
                    model_class.objects.get(id=self.object_id)
                except model_class.DoesNotExist:
                    raise ValidationError({'object_id': 'Can not attach a note to an instance that does not exists'})

        def set_obj_repr():
            """ set the object_repr """
            try:
                content_type_object = ContentType.objects.get(id=self.content_type_id)
                model_class = apps.get_model(app_label=content_type_object.app_label,
                                             model_name=content_type_object.model)
                content_instance = model_class.objects.get(id=self.object_id)
                self.object_repr = str(content_instance)
            except Exception as err:
                pass

        verify_object_instance_exists()
        set_obj_repr()

    def set_read_permission(self):
        """ automatically add the 'read' permission if scope is set to 'public' """
        if self.scope and self.scope.name == 'public':
                self.public_permissions.add(Permission.objects.get_or_create(name='read')[0])

    def get_icon(self):
        """ get a fontawesome icon based on the scope to use in the gui """
        icon_map = {
            'group': '<i class="fa-solid fa-people-group"></i>',
            'private': '<i class="fa-solid fa-user-secret"></i>',
            'public': '<i class="fa-solid fa-lock-open"></i>',
        }
        try:
             if self.scope.name in icon_map:
                return icon_map[self.scope.name]
             else:
                return '<i class="fas fa-file"></i>'
        except Exception as err:
            return '<i class="fa-regular fa-note-sticky"></i>'

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Note, self).save(*args, **kwargs)
        self.set_read_permission()

    def __str__(self):
        return self.title


class GroupPermission(HandyHelperBaseModel):
    """ through table to link permissions to groups on a note """
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    permissions = models.ManyToManyField(Permission, blank=True,
                                         help_text='actions that can be performed on a group scoped note')


class PublicPermission(HandyHelperBaseModel):
    """ through table to link public permissions on a note """
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    permission = models.ForeignKey(Permission, blank=True, null=True, on_delete=models.SET_NULL,
                                   help_text='actions that can be performed on a public scoped note')


if 'auditlog' in settings.INSTALLED_APPS:
    auditlog.register(Note)

src/djangoaddicts/modelnotes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'content', 'scope', 'groups', 'public_permissions']

src/modelnotes/forms.py
from django import forms

from modelnotes.models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'content', 'scope', 'groups', 'public_permissions']

src/djangoaddicts/modelnotes/views/action.py
from django.apps import apps
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.views.generic import View, DeleteView
from braces.views import LoginRequiredMixin


# import models
from django.contrib.auth.models import Group
from djangoaddicts.modelnotes.models import (Scope, Permission, Note)


def check_managability(user, note, action):
    """
    Determine if user can edit or delete this note. This note can be edited or deleted if at least one of the
    following criteria is met:
        - user is an admin
        - user is the author of the note
        - user is member of a group in groups AND note is proper permission is set
        - note is public and proper permission is set

    Args:
        user: django User object
        note: Note object
        action: (str) name of action to check for (edit or delete)

    Returns (bool):
        True if this note can be managed by the provided user
        False if this note can not be managed by the provided user
    """
    if action not in 'readeditdelete':
        return False
    if user.is_superuser:
        return True
    if note.author == user:
        return True
    if note.scope.name == 'group' and \
            any(i in user.groups.all() for i in note.groups.all()) and \
            action in [i.name for i in note.public_permissions.all()]:
        return True
    if note.scope.name == 'public' and action in [i.name for i in note.public_permissions.all()]:
        return True
    return False


class CreateNote(LoginRequiredMixin, View):
    """ create a note """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        label = self.request.GET.dict().get('model', None)
        obj_id = self.request.GET.dict().get('id', None)
        title = self.request.GET.dict().get('title', None)
        scope_name = self.request.GET.dict().get('scope', None)
        groups = self.request.GET.dict().get('groups', None)
        permissions = self.request.GET.dict().get('permissions', None)
        content = self.request.GET.dict().get('content', None)

        try:
            if scope_name:
                scope = Scope.objects.get(name=scope_name)
            else:
                scope = None
            note = Note.objects.create(
                title=title,
                author=request.user,
                scope=scope,
                content=content,
                content_type=ContentType.objects.get(app_label=label.split('.')[0], model=label.split('.')[1]),
                object_id=obj_id,
            )

            if scope.name == 'group':
                group_list = Group.objects.filter(name__in=groups.split(','))
                for group in group_list:
                    if group not in note.groups.all():
                        note.groups.add(group)

            elif scope.name == 'public':
                permission_list = Permission.objects.filter(name__in=permissions.split(','))
                for permission in permission_list:
                    if permission not in note.public_permissions.all():
                        note.public_permissions.add(permission)

            messages.add_message(self.request, messages.INFO, f'note {note} successfully created',
                                 extra_tags='alert-info')
        except Exception as err:
            messages.add_message(request, messages.ERROR, str(err), extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))


class UpdateNote(LoginRequiredMixin, View):
    """ update a note """
    def post(self, request, *args, **kwargs):
        """ process POST request """
        obj_id = self.request.GET.dict().get('id', None)
        title = self.request.GET.dict().get('title', None)
        scope_name = self.request.GET.dict().get('scope', None)
        groups = self.request.GET.dict().get('groups', None)
        permissions = self.request.GET.dict().get('permissions', None)
        content = self.request.GET.dict().get('content', None)
        new_groups = Group.objects.filter(name__in=groups.split(','))
        new_permissions = Permission.objects.filter(name__in=permissions.split(','))
        try:
            note = Note.objects.get_object_or_none(id=obj_id)
            scope = Scope.objects.get(name=scope_name)
            if check_managability(request.user, note, 'edit'):
                note.title = title
                note.scope = scope
                note.content = content

                # remove attached groups if note scope is not group
                if scope.name != 'group':
                    note.groups.remove(*note.groups.all())

                # remove attached public_permissions if note scope is not public
                if scope.name != 'public':
                    note.public_permissions.remove(*note.public_permissions.all())

                if scope.name == 'group':
                    for group in new_groups:
                        if group not in note.groups.all():
                            note.groups.add(group)
                    for group in note.groups.all():
                        if group not in new_groups:
                            note.groups.remove(group)

                if scope.name == 'public':
                    for permission in new_permissions:
                        if permission not in note.public_permissions.all():
                            note.public_permissions.add(permission)
                    for permission in note.public_permissions.all():
                        if permission not in new_permissions:
                            note.public_permissions.remove(permission)

                note.save()
                messages.add_message(self.request, messages.INFO, f'note {note} successfully updated',
                                     extra_tags='alert-info')
            else:
                messages.add_message(self.request, messages.ERROR, f'This note can not be updated by {request.user}',
                                     extra_tags='alert-danger')
        except Exception as err:
            messages.add_message(request, messages.ERROR, err, extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))


class DeleteNote(LoginRequiredMixin, DeleteView):
    """ delete a note (by pk) and return to the referring page """
    def delete(self, request, *args, **kwargs):
        note = Note.objects.get(**kwargs)
        if check_managability(request.user, note, 'delete'):
            note.delete()
            messages.add_message(self.request, messages.INFO, 'note successfully deleted', extra_tags='alert-info')
        else:
            messages.add_message(self.request, messages.ERROR, f'This note can not be deleted by {request.user}',
                                 extra_tags='alert-danger')
        return redirect(self.request.META.get('HTTP_REFERER'))

src/djangoaddicts/modelnotes/templates/modelnotes/form/create_note.htm
{# custom javascript and modal to support creating a note #}
{% load static %}
{% block page_javascript %}
    <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>

    <script language="Javascript">

        function CreateNote(url, header, button){
            /*
             Description:
                Launch modal to update note

             Parameters:
                 url         - url to access on confirmation
                 header      - modal window header
                 button	     - action button label
            */
            if (url === undefined){
                return;
            }
            if (header === undefined){
                var header = "Confirm";
            }
            if (button === undefined){
                var button = "Continue";
            }

            document.getElementById("id_modalCreateNoteHeader").innerHTML = "<b>"+header+"</b>";
            document.getElementById("id_modalCreateNote_OK").innerHTML = button;
            var okbutton = document.getElementById("id_modalCreateNote_OK");

            document.getElementById("id_modalCreateNote_OK").onclick = function(){postCreateNote(url);};
            showModal('id_modalCreateNote');
        }

        function postCreateNote(url){
            /*
             Description:
                Send a POST using #modalsubmitform down below. Creates action to input url.

             Parameters:
                url   - url to POST a blank form to.
            */
            var dummyform = $('#modalsubmitform');
            var title = document.getElementById("title").value;
            var scope = document.getElementById("id_scope_select").value;
            var content = document.getElementById("content").value;
            var permissions = $('#id_permission_select').val();
            var groups = $('#id_group_select').val();
            dummyform.attr('action', url+"&title="+title+"&scope="+scope+"&permissions="+permissions+"&content="+content+"&groups="+groups);
            dummyform.attr('method', 'POST');
            dummyform.submit();
        }

    </script>
{% endblock %}

<!-- MODAL: create note -->
<div id="id_modalCreateNoteWrapper">
    <div class="modal fade" id="id_modalCreateNote" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="id_modalCreateNoteHeader"></h4>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body" id="id_modalCreateNoteBody">
                    <form class="form-horizontal" role="form" action="">
                        <div class="form-group">
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="title"><b>Title:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <input type="text" class="form-control" id="title" name="title"/>
                                </div>
                            </div>
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="content"><b>Content:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <textarea rows="5" class="form-control" id="content" name="content"></textarea>
                                </div>
                            </div>
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="id_scope_select"><b>Scope:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <select class="form-control" id="id_scope_select" name="scope"
                                        hx-trigger="change"
                                        hx-get="{% url 'modelnotes:get_scope_fields' %}"
                                        hx-target="#id_select_options"
                                    >
                                        <option value="private" selected>private</option>
                                        <option value="public">public</option>
                                        <option value="group">group</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mt-2 row text-left" id="id_select_options"></div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer" id="id_modalCreateNoteFooter">
                    <button class="btn btn-light" data-bs-dismiss="modal" aria-hidden="true">Cancel</button>
                    <a class="btn btn-primary text-light" id="id_modalCreateNote_OK"></a>
                </div>
            </div>
        </div>
    </div>
</div>

src/djangoaddicts/modelnotes/templates/modelnotes/form/note_form.htm
<div class="mt-2 row text-left">
    <div class="col-sm-3 col-md-2">
        <label class="control-label" for="id_title"><b>Title:</b></label>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="text" name="title" value="{{ object.title }}" maxlength="32" placeholder="title for your note" class="form-control" required="" id="id_title">
    </div>
</div>
<div class="mt-2 row text-left">
    <div class="col-sm-3 col-md-2">
        <label class="control-label" for="id_content"><b>Content:</b></label>
    </div>
    <div class="col-sm-9 col-md-10">
        <textarea name="content" cols="40" rows="5" class="form-control" required="" id="id_content">{{ object.content }}</textarea>
    </div>
</div>
<div class="mt-2 row text-left">
    <div class="col-sm-3 col-md-2">
        <label class="control-label" for="id_scope"><b>Scope:</b></label>
    </div>
    <div class="col-sm-9 col-md-10">
        <select name="scope" class="form-control" id="id_scope"
            hx-trigger="load, change"
            hx-get="{% if object %}{% url 'modelnotes:get_scope_fields' object.id %}{% else %}{% url 'modelnotes:get_scope_fields' %}{% endif %}"
            hx-target="#id_select_options">
            <option value="">---------</option>
            <option value="1" {% if object.scope.name == "private" %}selected {% endif %}>private</option>
            <option value="2" {% if object.scope.name == "group" %}selected {% endif %}>group</option>
            <option value="3" {% if object.scope.name == "public" %}selected {% endif %}>public</option>
        </select>
    </div>
</div>
<div id="id_select_options"></div>

src/djangoaddicts/modelnotes/templates/modelnotes/form/update_note.htm
{# custom javascript and modal to support updating a note #}
{% load static %}
{% block page_javascript %}
    <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>

    <script language="Javascript">

        function UpdateNote(url, header, title, content, scope, permissions, groups, button){
            /*
             Description:
                Launch modal to update note

             Parameters:
                 url         - url to access on confirmation
                 header      - modal window header
                 title       - data in the 'title' textbox
                 content     - data in the 'content' textarea
                 scope       - data in the 'scope' selectbox
                 permissions - data in the 'permissions' selectbox
                 groups      - data in the 'groups' selectbox
                 button	     - action button label
            */
            if (url === undefined){
                return;
            }
            if (header === undefined){
                var header = "Confirm";
            }
            if (button === undefined){
                var button = "Continue";
            }

            document.getElementById("update_title").value = title;
            document.getElementById("update_scope").value = scope;
            document.getElementById("update_content").value = content;
            document.getElementById("id_modalUpdateNoteHeader").innerHTML = "<b>"+header+"</b>";
            document.getElementById("id_modalUpdateNote_OK").innerHTML = button;
            var okbutton = document.getElementById("id_modalUpdateNote_OK");

            document.getElementById("id_modalUpdateNote_OK").onclick = function(){postUpdateNote(url);};
            showModal('id_modalUpdateNote');
        }

        function postUpdateNote(url){
            /*
             Description:
                Send a POST using #modalsubmitform down below. Updates action to input url.

             Parameters:
                url   - url to POST a blank form to.
            */
            var dummyform = $('#modalsubmitform');
            var title = document.getElementById("update_title").value;
            var scope = document.getElementById("update_scope").value;
            var content = document.getElementById("update_content").value;
            var permissions = $('#update_permissions').val();
            var groups = $('#update_groups').val();
            dummyform.attr('action', url+"&title="+title+"&scope="+scope+"&permissions="+permissions+"&content="+content+"&groups="+groups);
            dummyform.attr('method', 'POST');
            dummyform.submit();
        }

    </script>
{% endblock %}

<!-- MODAL: update note -->
<div id="id_modalUpdateNoteWrapper">
    <div class="modal fade" id="id_modalUpdateNote" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="id_modalUpdateNoteHeader"></h4>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body" id="id_modalUpdateNoteBody">
                    <form class="form-horizontal" role="form" action="">
                        <div class="form-group">
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="update_title"><b>Title:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <input type="text" class="form-control" id="update_title" name="title"/>
                                </div>
                            </div>
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="update_content"><b>Content:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <textarea rows="5" class="form-control" id="update_content" name="content"></textarea>
                                </div>
                            </div>
                            <div class="mt-2 row text-left">
                                <div class="col-sm-3 col-md-2">
                                    <label class="control-label" for="update_scope"><b>Scope:</b></label>
                                </div>
                                <div class="col-sm-9 col-md-10">
                                    <select class="form-control" id="update_scope" name="scope">
                                        <option value="public">public</option>
                                        <option value="group">group</option>
                                        <option value="private">private</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mt-2 row text-left" id="id_update_select_options"></div>
                        </div>
                    </form>

                </div>
                <div class="modal-footer" id="id_modalUpdateNoteFooter">
                    <button class="btn btn-light" data-bs-dismiss="modal" aria-hidden="true">Cancel</button>
                    <a class="btn btn-primary text-light" id="id_modalUpdateNote_OK"></a>
                </div>
            </div>
        </div>
    </div>
</div>